from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainDW3000IPS(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainDW3000IPS):
        MainDW3000IPS.setObjectName("MainDW3000IPS")

        MainDW3000IPS.setGeometry(43, 83, 1280, 640)
        MainDW3000IPS.setFixedWidth(1280)
        MainDW3000IPS.setFixedHeight(640)

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        MainDW3000IPS.setFont(font)

        self.centralwidget = QtWidgets.QWidget(parent=MainDW3000IPS)
        self.centralwidget.setObjectName("centralwidget")

        self.label_Title_MW = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Title_MW.setGeometry(QtCore.QRect(10, 0, 1261, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        self.label_Title_MW.setFont(font)
        self.label_Title_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Title_MW.setObjectName("label_Title_MW")

        self.graphicsView_IPS_MW = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView_IPS_MW.setGeometry(QtCore.QRect(19, 60, 949, 411))
        self.graphicsView_IPS_MW.setObjectName("graphicsView_IPS_MW")

        self.horizontalScrollBar_IPS_MW = QtWidgets.QScrollBar(parent=self.centralwidget)
        self.horizontalScrollBar_IPS_MW.setGeometry(QtCore.QRect(25, 450, 915, 16))
        self.horizontalScrollBar_IPS_MW.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar_IPS_MW.setObjectName("horizontalScrollBar_IPS_MW")

        self.verticalScrollBar_IPS_MW = QtWidgets.QScrollBar(parent=self.centralwidget)
        self.verticalScrollBar_IPS_MW.setGeometry(QtCore.QRect(949, 65, 16, 381))
        self.verticalScrollBar_IPS_MW.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar_IPS_MW.setObjectName("verticalScrollBar_IPS_MW")

        self.label_RangingTag_MW = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_RangingTag_MW.setGeometry(QtCore.QRect(980, 190, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.label_RangingTag_MW.setFont(font)
        self.label_RangingTag_MW.setObjectName("label_RangingTag_MW")

        self.label_AnchorsPositions_MW = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_AnchorsPositions_MW.setGeometry(QtCore.QRect(980, 340, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.label_AnchorsPositions_MW.setFont(font)
        self.label_AnchorsPositions_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_AnchorsPositions_MW.setObjectName("label_AnchorsPositions_MW")

        self.layoutWidget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(980, 410, 74, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_Anchor_DAP = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_Anchor_DAP.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Anchor_DAP.setObjectName("verticalLayout_Anchor_DAP")

        self.label_AnchorsPosA1_MW = QtWidgets.QLabel(parent=self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_AnchorsPosA1_MW.setFont(font)
        self.label_AnchorsPosA1_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_AnchorsPosA1_MW.setObjectName("label_AnchorsPosA1_MW")
        self.verticalLayout_Anchor_DAP.addWidget(self.label_AnchorsPosA1_MW)

        self.label_AnchorsPosA2_MW = QtWidgets.QLabel(parent=self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_AnchorsPosA2_MW.setFont(font)
        self.label_AnchorsPosA2_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_AnchorsPosA2_MW.setObjectName("label_AnchorsPosA2_MW")
        self.verticalLayout_Anchor_DAP.addWidget(self.label_AnchorsPosA2_MW)

        self.label_AnchorsPosA3_MW = QtWidgets.QLabel(parent=self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_AnchorsPosA3_MW.setFont(font)
        self.label_AnchorsPosA3_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_AnchorsPosA3_MW.setObjectName("label_AnchorsPosA3_MW")
        self.verticalLayout_Anchor_DAP.addWidget(self.label_AnchorsPosA3_MW)
        self.label_ConnectedTime_MW = QtWidgets.QLabel(parent=self.centralwidget)

        self.label_ConnectedTime_MW.setGeometry(QtCore.QRect(980, 100, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.label_ConnectedTime_MW.setFont(font)
        self.label_ConnectedTime_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ConnectedTime_MW.setObjectName("label_ConnectedTime_MW")
        self.label_ConnectedTimeDisplay_MW = QtWidgets.QLabel(parent=self.centralwidget)

        self.label_ConnectedTimeDisplay_MW.setGeometry(QtCore.QRect(980, 140, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.label_ConnectedTimeDisplay_MW.setFont(font)
        self.label_ConnectedTimeDisplay_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ConnectedTimeDisplay_MW.setObjectName("label_ConnectedTimeDisplay_MW")

        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1060, 230, 208, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_checkBox_RT = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_checkBox_RT.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_checkBox_RT.setObjectName("horizontalLayout_checkBox_RT")

        self.checkBox_RangingTag1_MW = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.checkBox_RangingTag1_MW.setFont(font)
        self.checkBox_RangingTag1_MW.setObjectName("checkBox_RangingTag1_MW")
        self.horizontalLayout_checkBox_RT.addWidget(self.checkBox_RangingTag1_MW)

        self.checkBox_RangingTag2_MW = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.checkBox_RangingTag2_MW.setFont(font)
        self.checkBox_RangingTag2_MW.setObjectName("checkBox_RangingTag2_MW")
        self.horizontalLayout_checkBox_RT.addWidget(self.checkBox_RangingTag2_MW)

        self.checkBox_RangingTag3_MW = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.checkBox_RangingTag3_MW.setFont(font)
        self.checkBox_RangingTag3_MW.setObjectName("checkBox_RangingTag3_MW")
        self.horizontalLayout_checkBox_RT.addWidget(self.checkBox_RangingTag3_MW)

        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(980, 260, 74, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_labelRT_MW = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_labelRT_MW.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_labelRT_MW.setObjectName("verticalLayout_labelRT_MW")

        self.label_RangingTagA1_MW = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_RangingTagA1_MW.setFont(font)
        self.label_RangingTagA1_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RangingTagA1_MW.setObjectName("label_RangingTagA1_MW")
        self.verticalLayout_labelRT_MW.addWidget(self.label_RangingTagA1_MW)

        self.label_RangingTagA2_MW = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_RangingTagA2_MW.setFont(font)
        self.label_RangingTagA2_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RangingTagA2_MW.setObjectName("label_RangingTagA2_MW")
        self.verticalLayout_labelRT_MW.addWidget(self.label_RangingTagA2_MW)

        self.label_RangingTagA3_MW = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_RangingTagA3_MW.setFont(font)
        self.label_RangingTagA3_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RangingTagA3_MW.setObjectName("label_RangingTagA3_MW")
        self.verticalLayout_labelRT_MW.addWidget(self.label_RangingTagA3_MW)

        self.layoutWidget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(1060, 260, 211, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_ValueRT_MW = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_ValueRT_MW.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_ValueRT_MW.setObjectName("horizontalLayout_ValueRT_MW")
        self.verticalLayout_1stTag_MW = QtWidgets.QVBoxLayout()
        self.verticalLayout_1stTag_MW.setObjectName("verticalLayout_1stTag_MW")

        self.label_valuet1a1_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet1a1_MW.setFont(font)
        self.label_valuet1a1_MW.setObjectName("label_valuet1a1_MW")
        self.verticalLayout_1stTag_MW.addWidget(self.label_valuet1a1_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.label_valuet1a2_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet1a2_MW.setFont(font)
        self.label_valuet1a2_MW.setObjectName("label_valuet1a2_MW")
        self.verticalLayout_1stTag_MW.addWidget(self.label_valuet1a2_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.label_valuet1a3_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet1a3_MW.setFont(font)
        self.label_valuet1a3_MW.setObjectName("label_valuet1a3_MW")
        self.verticalLayout_1stTag_MW.addWidget(self.label_valuet1a3_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_ValueRT_MW.addLayout(self.verticalLayout_1stTag_MW)
        self.verticalLayout_2ndTag_RT_MW = QtWidgets.QVBoxLayout()
        self.verticalLayout_2ndTag_RT_MW.setObjectName("verticalLayout_2ndTag_RT_MW")

        self.label_valuet2a1_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet2a1_MW.setFont(font)
        self.label_valuet2a1_MW.setObjectName("label_valuet2a1_MW")
        self.verticalLayout_2ndTag_RT_MW.addWidget(self.label_valuet2a1_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.label_valuet2a2_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet2a2_MW.setFont(font)
        self.label_valuet2a2_MW.setObjectName("label_valuet2a2_MW")
        self.verticalLayout_2ndTag_RT_MW.addWidget(self.label_valuet2a2_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.label_valuet2a3_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet2a3_MW.setFont(font)
        self.label_valuet2a3_MW.setObjectName("label_valuet2a3_MW")
        self.verticalLayout_2ndTag_RT_MW.addWidget(self.label_valuet2a3_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_ValueRT_MW.addLayout(self.verticalLayout_2ndTag_RT_MW)
        self.verticalLayout_3rdTag_MW = QtWidgets.QVBoxLayout()
        self.verticalLayout_3rdTag_MW.setObjectName("verticalLayout_3rdTag_MW")

        self.label_valuet3a1_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet3a1_MW.setFont(font)
        self.label_valuet3a1_MW.setObjectName("label_valuet3a1_MW")
        self.verticalLayout_3rdTag_MW.addWidget(self.label_valuet3a1_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.label_valuet3a2_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet3a2_MW.setFont(font)
        self.label_valuet3a2_MW.setObjectName("label_valuet3a2_MW")
        self.verticalLayout_3rdTag_MW.addWidget(self.label_valuet3a2_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.label_valuet3a3_MW = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_valuet3a3_MW.setFont(font)
        self.label_valuet3a3_MW.setObjectName("label_valuet3a3_MW")
        self.verticalLayout_3rdTag_MW.addWidget(self.label_valuet3a3_MW, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_ValueRT_MW.addLayout(self.verticalLayout_3rdTag_MW)

        self.layoutWidget3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(1060, 380, 211, 21))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.label_xpos_MW = QtWidgets.QLabel(parent=self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_xpos_MW.setFont(font)
        self.label_xpos_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_xpos_MW.setObjectName("label_xpos_MW")
        self.horizontalLayout_3.addWidget(self.label_xpos_MW)

        self.label_ypos_MW = QtWidgets.QLabel(parent=self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_ypos_MW.setFont(font)
        self.label_ypos_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ypos_MW.setObjectName("label_ypos_MW")
        self.horizontalLayout_3.addWidget(self.label_ypos_MW)

        self.layoutWidget4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(1060, 410, 211, 71))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_DAP_X = QtWidgets.QVBoxLayout()
        self.verticalLayout_DAP_X.setObjectName("verticalLayout_DAP_X")

        self.label_x1_MW = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_x1_MW.setFont(font)
        self.label_x1_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_x1_MW.setObjectName("label_x1_MW")
        self.verticalLayout_DAP_X.addWidget(self.label_x1_MW)

        self.label_x2_MW = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_x2_MW.setFont(font)
        self.label_x2_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_x2_MW.setObjectName("label_x2_MW")
        self.verticalLayout_DAP_X.addWidget(self.label_x2_MW)

        self.label_x3_MW = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_x3_MW.setFont(font)
        self.label_x3_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_x3_MW.setObjectName("label_x3_MW")
        self.verticalLayout_DAP_X.addWidget(self.label_x3_MW)
        self.horizontalLayout_4.addLayout(self.verticalLayout_DAP_X)
        self.verticalLayout_DAP_Y = QtWidgets.QVBoxLayout()
        self.verticalLayout_DAP_Y.setObjectName("verticalLayout_DAP_Y")

        self.label_y1_MW = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_y1_MW.setFont(font)
        self.label_y1_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_y1_MW.setObjectName("label_y1_MW")
        self.verticalLayout_DAP_Y.addWidget(self.label_y1_MW)

        self.label_y2_MW = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_y2_MW.setFont(font)
        self.label_y2_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_y2_MW.setObjectName("label_y2_MW")
        self.verticalLayout_DAP_Y.addWidget(self.label_y2_MW)

        self.label_y3_MW = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.label_y3_MW.setFont(font)
        self.label_y3_MW.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_y3_MW.setObjectName("label_y3_MW")
        self.verticalLayout_DAP_Y.addWidget(self.label_y3_MW)
        self.horizontalLayout_4.addLayout(self.verticalLayout_DAP_Y)

        self.label_SerialSettings_CS = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_SerialSettings_CS.setGeometry(QtCore.QRect(300, 472, 114, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.label_SerialSettings_CS.setFont(font)
        self.label_SerialSettings_CS.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_SerialSettings_CS.setObjectName("label_SerialSettings_CS")

        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 530, 281, 85))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_checkBox_AP = QtWidgets.QVBoxLayout()
        self.verticalLayout_checkBox_AP.setObjectName("verticalLayout_checkBox_AP")

        self.checkBox_1AP = QtWidgets.QCheckBox(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        self.checkBox_1AP.setFont(font)
        self.checkBox_1AP.setObjectName("checkBox_1AP")
        self.verticalLayout_checkBox_AP.addWidget(self.checkBox_1AP)

        self.checkBox_2AP = QtWidgets.QCheckBox(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        self.checkBox_2AP.setFont(font)
        self.checkBox_2AP.setObjectName("checkBox_2AP")
        self.verticalLayout_checkBox_AP.addWidget(self.checkBox_2AP)

        self.checkBox_3AP = QtWidgets.QCheckBox(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        self.checkBox_3AP.setFont(font)
        self.checkBox_3AP.setObjectName("checkBox_3AP")
        self.verticalLayout_checkBox_AP.addWidget(self.checkBox_3AP)
        self.horizontalLayout_8.addLayout(self.verticalLayout_checkBox_AP)
        self.verticalLayout_lineEditX_AP = QtWidgets.QVBoxLayout()
        self.verticalLayout_lineEditX_AP.setObjectName("verticalLayout_lineEditX_AP")

        self.lineEdit_x1AP = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.lineEdit_x1AP.setFont(font)
        self.lineEdit_x1AP.setObjectName("lineEdit_x1AP")
        self.verticalLayout_lineEditX_AP.addWidget(self.lineEdit_x1AP)

        self.lineEdit_x2AP = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.lineEdit_x2AP.setFont(font)
        self.lineEdit_x2AP.setObjectName("lineEdit_x2AP")
        self.verticalLayout_lineEditX_AP.addWidget(self.lineEdit_x2AP)

        self.lineEdit_x3AP = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.lineEdit_x3AP.setFont(font)
        self.lineEdit_x3AP.setObjectName("lineEdit_x3AP")
        self.verticalLayout_lineEditX_AP.addWidget(self.lineEdit_x3AP)
        self.horizontalLayout_8.addLayout(self.verticalLayout_lineEditX_AP)
        self.verticalLayout_lineEditY_AP = QtWidgets.QVBoxLayout()
        self.verticalLayout_lineEditY_AP.setObjectName("verticalLayout_lineEditY_AP")

        self.lineEdit_y1AP = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.lineEdit_y1AP.setFont(font)
        self.lineEdit_y1AP.setObjectName("lineEdit_y1AP")
        self.verticalLayout_lineEditY_AP.addWidget(self.lineEdit_y1AP)

        self.lineEdit_y2AP = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.lineEdit_y2AP.setFont(font)
        self.lineEdit_y2AP.setObjectName("lineEdit_y2AP")
        self.verticalLayout_lineEditY_AP.addWidget(self.lineEdit_y2AP)

        self.lineEdit_y3AP = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.lineEdit_y3AP.setFont(font)
        self.lineEdit_y3AP.setObjectName("lineEdit_y3AP")
        self.verticalLayout_lineEditY_AP.addWidget(self.lineEdit_y3AP)
        self.horizontalLayout_8.addLayout(self.verticalLayout_lineEditY_AP)

        self.label_AreaCover_AC = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_AreaCover_AC.setGeometry(QtCore.QRect(630, 472, 90, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.label_AreaCover_AC.setFont(font)
        self.label_AreaCover_AC.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_AreaCover_AC.setObjectName("label_AreaCover_AC")

        self.layoutWidget_7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(110, 500, 181, 20))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_x_y_posAP = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_x_y_posAP.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_x_y_posAP.setObjectName("horizontalLayout_x_y_posAP")

        self.label_xpos_AP = QtWidgets.QLabel(parent=self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.label_xpos_AP.setFont(font)
        self.label_xpos_AP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_xpos_AP.setObjectName("label_xpos_AP")
        self.horizontalLayout_x_y_posAP.addWidget(self.label_xpos_AP)

        self.label_ypos_AP = QtWidgets.QLabel(parent=self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.label_ypos_AP.setFont(font)
        self.label_ypos_AP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ypos_AP.setObjectName("label_ypos_AP")
        self.horizontalLayout_x_y_posAP.addWidget(self.label_ypos_AP)

        self.label_AnchorsParameters_AP = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_AnchorsParameters_AP.setGeometry(QtCore.QRect(12, 472, 165, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.label_AnchorsParameters_AP.setFont(font)
        self.label_AnchorsParameters_AP.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_AnchorsParameters_AP.setObjectName("label_AnchorsParameters_AP")

        self.layoutWidget5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(1190, 510, 77, 89))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_FunctionSRS = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_FunctionSRS.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_FunctionSRS.setObjectName("verticalLayout_FunctionSRS")

        self.pushButton_SET_CS = QtWidgets.QPushButton(parent=self.layoutWidget5)
        self.pushButton_SET_CS.setObjectName("pushButton_SET_CS")
        self.verticalLayout_FunctionSRS.addWidget(self.pushButton_SET_CS)
        self.pushButton_SET_CS.setEnabled(False)

        self.pushButton_RESET_CS = QtWidgets.QPushButton(parent=self.layoutWidget5)
        self.pushButton_RESET_CS.setObjectName("pushButton_RESET_CS")
        self.verticalLayout_FunctionSRS.addWidget(self.pushButton_RESET_CS)
        self.pushButton_RESET_CS.setEnabled(False)

        self.pushButton_SAVE_CS = QtWidgets.QPushButton(parent=self.layoutWidget5)
        self.pushButton_SAVE_CS.setObjectName("pushButton_SAVE_CS")
        self.verticalLayout_FunctionSRS.addWidget(self.pushButton_SAVE_CS)
        self.pushButton_SAVE_CS.setEnabled(False)

        self.label_StatusConnection_MW = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_StatusConnection_MW.setGeometry(QtCore.QRect(981, 61, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_StatusConnection_MW.setFont(font)
        self.label_StatusConnection_MW.setObjectName("label_StatusConnection_MW")

        self.label_StatusConnectionResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_StatusConnectionResult.setGeometry(QtCore.QRect(1070, 60, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.label_StatusConnectionResult.setFont(font)
        self.label_StatusConnectionResult.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_StatusConnectionResult.setObjectName("label_StatusConnectionResult")

        self.horizontalSlider_ZoomInOut = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider_ZoomInOut.setGeometry(QtCore.QRect(30, 70, 160, 22))
        self.horizontalSlider_ZoomInOut.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_ZoomInOut.setObjectName("horizontalSlider_ZoomInOut")

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(720, 498, 121, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.lineEdit_lengthResult_AC = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.lineEdit_lengthResult_AC.setFont(font)
        self.lineEdit_lengthResult_AC.setObjectName("lineEdit_lengthResult_AC")
        self.horizontalLayout.addWidget(self.lineEdit_lengthResult_AC)

        self.label_length_AC_ = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_length_AC_.setFont(font)
        self.label_length_AC_.setObjectName("label_length_AC_")
        self.horizontalLayout.addWidget(self.label_length_AC_)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.lineEdit_widthResult_AC = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.lineEdit_widthResult_AC.setFont(font)
        self.lineEdit_widthResult_AC.setObjectName("lineEdit_widthResult_AC")
        self.horizontalLayout_2.addWidget(self.lineEdit_widthResult_AC)

        self.label_width_AC_meter = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_width_AC_meter.setFont(font)
        self.label_width_AC_meter.setObjectName("label_width_AC_meter")
        self.horizontalLayout_2.addWidget(self.label_width_AC_meter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.lineEdit_gridResult_AC = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        self.lineEdit_gridResult_AC.setFont(font)
        self.lineEdit_gridResult_AC.setObjectName("lineEdit_gridResult_AC")
        self.horizontalLayout_5.addWidget(self.lineEdit_gridResult_AC)

        self.label_grid_AC_meter = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_grid_AC_meter.setFont(font)
        self.label_grid_AC_meter.setObjectName("label_grid_AC_meter")
        self.horizontalLayout_5.addWidget(self.label_grid_AC_meter)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(630, 501, 83, 77))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label_length_AC = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_length_AC.setFont(font)
        self.label_length_AC.setObjectName("label_length_AC")
        self.verticalLayout_2.addWidget(self.label_length_AC)

        self.label_width_AC = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_width_AC.setFont(font)
        self.label_width_AC.setObjectName("label_width_AC")
        self.verticalLayout_2.addWidget(self.label_width_AC)

        self.label_grid_AC = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_grid_AC.setFont(font)
        self.label_grid_AC.setObjectName("label_grid_AC")
        self.verticalLayout_2.addWidget(self.label_grid_AC)

        self.label_COM_CS = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_COM_CS.setGeometry(QtCore.QRect(301, 501, 44, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_COM_CS.setFont(font)
        self.label_COM_CS.setObjectName("label_COM_CS")

        self.comboBox_COM_CS = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_COM_CS.setGeometry(QtCore.QRect(351, 501, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_COM_CS.setFont(font)
        self.comboBox_COM_CS.setObjectName("comboBox_COM_CS")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.setItemText(0, "")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")
        self.comboBox_COM_CS.addItem("")

        self.label_Baudrate_CS = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Baudrate_CS.setGeometry(QtCore.QRect(446, 501, 75, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_Baudrate_CS.setFont(font)
        self.label_Baudrate_CS.setObjectName("label_Baudrate_CS")

        self.comboBox_Baudrate_CS = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_Baudrate_CS.setGeometry(QtCore.QRect(527, 501, 81, 19))
        self.comboBox_Baudrate_CS.setObjectName("comboBox_Baudrate_CS")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.setItemText(0, "")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")
        self.comboBox_Baudrate_CS.addItem("")

        self.verticalScrollBar_IPS_MW.raise_()
        self.horizontalScrollBar_IPS_MW.raise_()
        self.label_Title_MW.raise_()
        self.label_RangingTag_MW.raise_()
        self.label_AnchorsPositions_MW.raise_()
        self.layoutWidget_4.raise_()
        self.label_ConnectedTime_MW.raise_()
        self.label_ConnectedTimeDisplay_MW.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_SerialSettings_CS.raise_()
        self.layoutWidget_2.raise_()
        self.label_AreaCover_AC.raise_()
        self.layoutWidget_7.raise_()
        self.label_AnchorsParameters_AP.raise_()
        self.layoutWidget.raise_()
        self.label_StatusConnection_MW.raise_()
        self.label_StatusConnectionResult.raise_()
        self.graphicsView_IPS_MW.raise_()
        self.horizontalSlider_ZoomInOut.raise_()
        self.label_length_AC_.raise_()
        self.lineEdit_widthResult_AC.raise_()
        self.label_width_AC.raise_()
        self.label_width_AC_meter.raise_()
        self.label_grid_AC.raise_()
        MainDW3000IPS.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainDW3000IPS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        MainDW3000IPS.setMenuBar(self.menubar)

        self.actionAnchors_Parameters = QtGui.QAction(parent=MainDW3000IPS)
        self.actionAnchors_Parameters.setObjectName("actionAnchors_Parameters")

        self.actionCOM_Serial = QtGui.QAction(parent=MainDW3000IPS)
        self.actionCOM_Serial.setObjectName("actionCOM_Serial")

        self.actionGraphs_RT = QtGui.QAction(parent=MainDW3000IPS)
        self.actionGraphs_RT.setObjectName("actionGraphs_RT")

        self.actionCharts_RT = QtGui.QAction(parent=MainDW3000IPS)
        self.actionCharts_RT.setObjectName("actionCharts_RT")

        self.actionDW3000_Settings = QtGui.QAction(parent=MainDW3000IPS)
        self.actionDW3000_Settings.setObjectName("actionDW3000_Settings")

        self.actionAbout_DW3000 = QtGui.QAction(parent=MainDW3000IPS)
        self.actionAbout_DW3000.setObjectName("actionAbout_DW3000")

        self.actionSave = QtGui.QAction(parent=MainDW3000IPS)
        self.actionSave.setObjectName("actionSave")

        self.actionNew = QtGui.QAction(parent=MainDW3000IPS)
        self.actionNew.setObjectName("actionNew")

        self.actionOpen = QtGui.QAction(parent=MainDW3000IPS)
        self.actionOpen.setObjectName("actionOpen")

        self.actionSave_As = QtGui.QAction(parent=MainDW3000IPS)
        self.actionSave_As.setObjectName("actionSave_As")

        self.actionExit_and_Save = QtGui.QAction(parent=MainDW3000IPS)
        self.actionExit_and_Save.setObjectName("actionExit_and_Save")

        self.actionExit = QtGui.QAction(parent=MainDW3000IPS)
        self.actionExit.setObjectName("actionExit")

        self.actionArea_Covers = QtGui.QAction(parent=MainDW3000IPS)
        self.actionArea_Covers.setObjectName("actionArea_Covers")

        self.actionGraphs_1AP = QtGui.QAction(parent=MainDW3000IPS)
        self.actionGraphs_1AP.setObjectName("actionGraphs_1AP")
        self.actionCharts_1AP = QtGui.QAction(parent=MainDW3000IPS)
        self.actionCharts_1AP.setObjectName("actionCharts_1AP")

        self.actionGraphs_2AP = QtGui.QAction(parent=MainDW3000IPS)
        self.actionGraphs_2AP.setObjectName("actionGraphs_2AP")

        self.actionCharts_2AP = QtGui.QAction(parent=MainDW3000IPS)
        self.actionCharts_2AP.setObjectName("actionCharts_2AP")

        self.actionGraphs_3AP = QtGui.QAction(parent=MainDW3000IPS)
        self.actionGraphs_3AP.setObjectName("actionGraphs_3AP")

        self.actionCharts_3AP = QtGui.QAction(parent=MainDW3000IPS)
        self.actionCharts_3AP.setObjectName("actionCharts_3AP")

        self.action1st_Anchors = QtGui.QAction(parent=MainDW3000IPS)
        self.action1st_Anchors.setObjectName("action1st_Anchors")

        self.action2nd_Anchors = QtGui.QAction(parent=MainDW3000IPS)
        self.action2nd_Anchors.setObjectName("action2nd_Anchors")

        self.action3rd_Anchor = QtGui.QAction(parent=MainDW3000IPS)
        self.action3rd_Anchor.setObjectName("action3rd_Anchor")

        self.actionTable_AE = QtGui.QAction(parent=MainDW3000IPS)
        self.actionTable_AE.setObjectName("actionTable_AE")

        self.actionGraphs_AE = QtGui.QAction(parent=MainDW3000IPS)
        self.actionGraphs_AE.setObjectName("actionGraphs_AE")

        self.actionCharts_AE = QtGui.QAction(parent=MainDW3000IPS)
        self.actionCharts_AE.setObjectName("actionCharts_AE")

        self.retranslateUi(MainDW3000IPS)
        QtCore.QMetaObject.connectSlotsByName(MainDW3000IPS)

    def retranslateUi(self, MainDW3000IPS):
        _translate = QtCore.QCoreApplication.translate

        # Adding the app's icon
        icon = QtGui.QIcon('images/ips.png')
        MainDW3000IPS.setWindowIcon(icon)

        MainDW3000IPS.setWindowTitle(_translate("MainDW3000IPS", "DW3000 Indoor Positioning System v1.0"))

        self.label_Title_MW.setText(_translate("MainDW3000IPS", "DW3000 Indoor Positioning System"))
        self.label_RangingTag_MW.setText(_translate("MainDW3000IPS", "Ranging Tag"))
        self.label_AnchorsPositions_MW.setText(_translate("MainDW3000IPS", "Anchors Positions"))
        self.label_AnchorsPosA1_MW.setText(_translate("MainDW3000IPS", "1st Anchor :"))
        self.label_AnchorsPosA2_MW.setText(_translate("MainDW3000IPS", "2nd Anchor :"))
        self.label_AnchorsPosA3_MW.setText(_translate("MainDW3000IPS", "3rd Anchor :"))
        self.label_ConnectedTime_MW.setText(_translate("MainDW3000IPS", "CONNECTED TIME"))
        self.label_ConnectedTimeDisplay_MW.setText(_translate("MainDW3000IPS", "00 : 00 : 00"))
        self.checkBox_RangingTag1_MW.setText(_translate("MainDW3000IPS", "1st Tag"))
        self.checkBox_RangingTag2_MW.setText(_translate("MainDW3000IPS", "2nd Tag"))
        self.checkBox_RangingTag3_MW.setText(_translate("MainDW3000IPS", "3rd Tag"))
        self.label_RangingTagA1_MW.setText(_translate("MainDW3000IPS", "1st Anchor :"))
        self.label_RangingTagA2_MW.setText(_translate("MainDW3000IPS", "2nd Anchor :"))
        self.label_RangingTagA3_MW.setText(_translate("MainDW3000IPS", "3rd Anchor :"))
        self.label_valuet1a1_MW.setText(_translate("MainDW3000IPS", "t1a1"))
        self.label_valuet1a2_MW.setText(_translate("MainDW3000IPS", "t1a2"))
        self.label_valuet1a3_MW.setText(_translate("MainDW3000IPS", "t1a3"))
        self.label_valuet2a1_MW.setText(_translate("MainDW3000IPS", "t2a1"))
        self.label_valuet2a2_MW.setText(_translate("MainDW3000IPS", "t2a2"))
        self.label_valuet2a3_MW.setText(_translate("MainDW3000IPS", "t2a3"))
        self.label_valuet3a1_MW.setText(_translate("MainDW3000IPS", "t3a1"))
        self.label_valuet3a2_MW.setText(_translate("MainDW3000IPS", "t3a2"))
        self.label_valuet3a3_MW.setText(_translate("MainDW3000IPS", "t3a3"))
        self.label_xpos_MW.setText(_translate("MainDW3000IPS", "x-position"))
        self.label_ypos_MW.setText(_translate("MainDW3000IPS", "y-position"))
        self.label_x1_MW.setText(_translate("MainDW3000IPS", "x1"))
        self.label_x2_MW.setText(_translate("MainDW3000IPS", "x2"))
        self.label_x3_MW.setText(_translate("MainDW3000IPS", "x3"))
        self.label_y1_MW.setText(_translate("MainDW3000IPS", "y1"))
        self.label_y2_MW.setText(_translate("MainDW3000IPS", "y2"))
        self.label_y3_MW.setText(_translate("MainDW3000IPS", "y3"))
        self.label_SerialSettings_CS.setText(_translate("MainDW3000IPS", "Serial Settings"))
        self.checkBox_1AP.setText(_translate("MainDW3000IPS", "1st Anchor"))
        self.checkBox_2AP.setText(_translate("MainDW3000IPS", "2nd Anchor"))
        self.checkBox_3AP.setText(_translate("MainDW3000IPS", "3rd Anchor"))
        self.label_AreaCover_AC.setText(_translate("MainDW3000IPS", "Area Cover"))
        self.label_xpos_AP.setText(_translate("MainDW3000IPS", "x-position"))
        self.label_ypos_AP.setText(_translate("MainDW3000IPS", "y-position"))
        self.label_AnchorsParameters_AP.setText(_translate("MainDW3000IPS", "Anchors Parameters"))
        self.pushButton_SET_CS.setText(_translate("MainDW3000IPS", "SET"))
        self.pushButton_RESET_CS.setText(_translate("MainDW3000IPS", "RESET"))
        self.pushButton_SAVE_CS.setText(_translate("MainDW3000IPS", "SAVE"))
        self.label_StatusConnection_MW.setText(_translate("MainDW3000IPS", "STATUS :"))
        self.label_StatusConnectionResult.setText(_translate("MainDW3000IPS", "CONNECTED"))
        self.label_length_AC_.setText(_translate("MainDW3000IPS", "meter"))
        self.label_width_AC_meter.setText(_translate("MainDW3000IPS", "meter"))
        self.label_grid_AC_meter.setText(_translate("MainDW3000IPS", "meter"))
        self.label_length_AC.setText(_translate("MainDW3000IPS", "Length :"))
        self.label_width_AC.setText(_translate("MainDW3000IPS", "Width :"))
        self.label_grid_AC.setText(_translate("MainDW3000IPS", "Grid Scale :"))
        self.label_COM_CS.setText(_translate("MainDW3000IPS", "COM :"))
        self.comboBox_COM_CS.setItemText(1, _translate("MainDW3000IPS", "COM1"))
        self.comboBox_COM_CS.setItemText(2, _translate("MainDW3000IPS", "COM2"))
        self.comboBox_COM_CS.setItemText(3, _translate("MainDW3000IPS", "COM3"))
        self.comboBox_COM_CS.setItemText(4, _translate("MainDW3000IPS", "COM4"))
        self.comboBox_COM_CS.setItemText(5, _translate("MainDW3000IPS", "COM5"))
        self.comboBox_COM_CS.setItemText(6, _translate("MainDW3000IPS", "COM6"))
        self.comboBox_COM_CS.setItemText(7, _translate("MainDW3000IPS", "COM7"))
        self.comboBox_COM_CS.setItemText(8, _translate("MainDW3000IPS", "COM8"))
        self.comboBox_COM_CS.setItemText(9, _translate("MainDW3000IPS", "COM9"))
        self.comboBox_COM_CS.setItemText(10, _translate("MainDW3000IPS", "COM10"))
        self.label_Baudrate_CS.setText(_translate("MainDW3000IPS", "Baudrate :"))
        self.comboBox_Baudrate_CS.setItemText(1, _translate("MainDW3000IPS", "300"))
        self.comboBox_Baudrate_CS.setItemText(2, _translate("MainDW3000IPS", "600"))
        self.comboBox_Baudrate_CS.setItemText(3, _translate("MainDW3000IPS", "750"))
        self.comboBox_Baudrate_CS.setItemText(4, _translate("MainDW3000IPS", "1200"))
        self.comboBox_Baudrate_CS.setItemText(5, _translate("MainDW3000IPS", "2400"))
        self.comboBox_Baudrate_CS.setItemText(6, _translate("MainDW3000IPS", "4800"))
        self.comboBox_Baudrate_CS.setItemText(7, _translate("MainDW3000IPS", "9600"))
        self.comboBox_Baudrate_CS.setItemText(8, _translate("MainDW3000IPS", "19200"))
        self.comboBox_Baudrate_CS.setItemText(9, _translate("MainDW3000IPS", "31250"))
        self.comboBox_Baudrate_CS.setItemText(10, _translate("MainDW3000IPS", "38400"))
        self.comboBox_Baudrate_CS.setItemText(11, _translate("MainDW3000IPS", "57600"))
        self.comboBox_Baudrate_CS.setItemText(12, _translate("MainDW3000IPS", "74880"))
        self.comboBox_Baudrate_CS.setItemText(13, _translate("MainDW3000IPS", "115200"))
        self.comboBox_Baudrate_CS.setItemText(14, _translate("MainDW3000IPS", "230400"))
        self.comboBox_Baudrate_CS.setItemText(15, _translate("MainDW3000IPS", "250000"))
        self.comboBox_Baudrate_CS.setItemText(16, _translate("MainDW3000IPS", "460800"))
        self.comboBox_Baudrate_CS.setItemText(17, _translate("MainDW3000IPS", "500000"))
        self.comboBox_Baudrate_CS.setItemText(18, _translate("MainDW3000IPS", "921600"))
        self.comboBox_Baudrate_CS.setItemText(19, _translate("MainDW3000IPS", "1000000"))
        self.comboBox_Baudrate_CS.setItemText(20, _translate("MainDW3000IPS", "2000000"))
        self.actionAnchors_Parameters.setText(_translate("MainDW3000IPS", "Anchors Parameters"))
        self.actionCOM_Serial.setText(_translate("MainDW3000IPS", "COM Serial"))
        self.actionGraphs_RT.setText(_translate("MainDW3000IPS", "Graphs"))
        self.actionCharts_RT.setText(_translate("MainDW3000IPS", "Charts"))
        self.actionDW3000_Settings.setText(_translate("MainDW3000IPS", "DW3000 Settings"))
        self.actionAbout_DW3000.setText(_translate("MainDW3000IPS", "About DW3000"))
        self.actionSave.setText(_translate("MainDW3000IPS", "Save"))
        self.actionNew.setText(_translate("MainDW3000IPS", "New"))
        self.actionOpen.setText(_translate("MainDW3000IPS", "Open"))
        self.actionSave_As.setText(_translate("MainDW3000IPS", "Save As"))
        self.actionExit_and_Save.setText(_translate("MainDW3000IPS", "Exit and Save"))
        self.actionExit.setText(_translate("MainDW3000IPS", "Exit"))
        self.actionArea_Covers.setText(_translate("MainDW3000IPS", "Area Cover"))
        self.actionGraphs_1AP.setText(_translate("MainDW3000IPS", "Graphs"))
        self.actionCharts_1AP.setText(_translate("MainDW3000IPS", "Charts"))
        self.actionGraphs_2AP.setText(_translate("MainDW3000IPS", "Graphs"))
        self.actionCharts_2AP.setText(_translate("MainDW3000IPS", "Charts"))
        self.actionGraphs_3AP.setText(_translate("MainDW3000IPS", "Graphs"))
        self.actionCharts_3AP.setText(_translate("MainDW3000IPS", "Charts"))
        self.action1st_Anchors.setText(_translate("MainDW3000IPS", "1st Anchor"))
        self.action2nd_Anchors.setText(_translate("MainDW3000IPS", "2nd Anchor"))
        self.action3rd_Anchor.setText(_translate("MainDW3000IPS", "3rd Anchor"))
        self.actionTable_AE.setText(_translate("MainDW3000IPS", "Tables"))
        self.actionGraphs_AE.setText(_translate("MainDW3000IPS", "Graphs"))
        self.actionCharts_AE.setText(_translate("MainDW3000IPS", "Charts"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainDW3000IPS = QtWidgets.QMainWindow()
    ui = Ui_MainDW3000IPS()
    ui.setupUi(MainDW3000IPS)
    MainDW3000IPS.show()
    sys.exit(app.exec())
